### ISSUE TITLE
Not support local hosts file?

### ISSUE THREAD

**Issue by deepseeksss** [partim/domain#12]
for linux: /etc/hosts

**Comment by partim** [comment]
I tend to not want to support this in the `domain` crate since it is intended for DNS only.

What I would like to do instead is start a new crate that mimics NSS and not only considers `/etc/hosts` but also `/etc/nsswitch.conf` and perhaps even allows binding NSS `.so` libraries. An initial version could only provide name resolution with DNS and the hosts file, to make this functionality available quickly.

How does that sound?

**Comment by deepseeksss** [comment]
i think it is not easy to program,  because of we don't know the end-user's system environment, there must someone want to use hosts file directly, like me? As a programmer, we should use two crates's functions to resolve the host name? i suggest integrated into domain, just like c api, gethostbyname

**Comment by partim** [comment]
Sorry, I was unclear: The idea is to provide a single crate that performs the lookups such as that performed by `gethostbyname()` in a simple way and correctly for whatever platform you are on.

Ie., you wouldn't be using `domain` at all anymore but only that new crate.

**Comment by tailhook** [comment]
Binding to `.so` in async program doesn't make sense. Either use `gethostbyname()` directly (in a thread) or make normal async resolver with things that's possible to do asynchronously.

**Comment by partim** [comment]
In pretty much all setups the `nsswitch.conf` entry for hosts is effectively `files dns` (safe for alternative resolvers which can be translated into appropriate `domain` configuration once it supports whatever additional functionality those resolvers provide). It would still be nice if packages could behave correctly in the fraction of cases that differ. For instance, if I removed the `files` entry from `nsswitch.conf` (because I have a complex `hosts` file which I want to disable temporarily), it would be nice it Things Just Worked.

For async use, the `.so` bindings could be forked into a thread pool.

**Comment by tailhook** [comment]
Well, here is the stock `nsswitch.conf` from nix:
```
hosts:     files  dns   myhostname mymachines
```
`mdns` and `mdns_minimal` are also common (as allows service discovery, e.g. to find printers as easy as on other OSs)
`systemd` is also going to gain popularity just because it's installed everywhere
I'm not sure about `ldap`

**Comment by partim** [comment]
Most of this should be supported by the new crate natively, perhaps even `ldap` if we have an underlying crate for it—a protocol as complex as LDAP would particularly benefit from using a Rust implementation.

**Comment by tailhook** [comment]
Yes. That would be great. But it's a hell of a lot of work :)

**Comment by partim** [comment]
I’m happy to at least get started. I am somewhat busy with life stuff the next weeks, though, but I’ll start a crate that pulls together the hosts file stuff (a parser for which actually is already present in `domain`) and the resolver, sometime soon. That will hopefully solve @Matrix-Zhang’s use case and then we can see where we go from there.

**Comment by deepseeksss** [comment]
I see, thanks for your hard wrok

**Comment by partim** [comment]
Quick update: I started the [netdb](https://github.com/partim/netdb) crate and put together a preliminary implementation of `get_host_by_name()` and its async companion, tentatively named `poll_host_by_name()`. Needs testing and documenting and examples before it can go onto crates.io even in its really limited state, though.

**Comment by zonyitoo** [comment]
@partim what's the status of `netdb` crate?

**Comment by partim** [comment]
I’ve been caught up in moving the last two weeks but things have calmed down now. Hoping to get the remaining stuff done perhaps this weekend already, otherwise early next week.

**Comment by partim** [comment]
Version 0.1.0 of `netdb` has just been uploaded to `crates.io`. It really only is a start just now, but it should allow closing this issue.
