### ISSUE TITLE
Any plans to publish on crates.io?

### ISSUE THREAD

**Issue by tailhook** [partim/domain#2]
Hi,

I'm [experimenting](https://github.com/tailhook/abstract-ns/tree/master/ns-dns-tokio) with `domain` as a part of my effort to make [generic/pluggable name resolution for tokio](https://github.com/tailhook/abstract-ns).  It would be easier to play with the library if it was published on the crates.io.

So are there issues with that?

**Comment by partim** [comment]
I’m currently in [a big re-factoring of the bits module](https://github.com/partim/domain/tree/refactored-bits) as a result of actually using it for real in the resolver. As there’s only documentation and some tests left, that should be done quite soon.

After that, I’m planning on doing some more thorough tests on the resolver since so far I’ve only quickly checked the happy path.

Once I’m convinced that the resolver actually does what it says on the box, I’m happy to release 0.1.

**Comment by partim** [comment]
[There!](https://crates.io/crates/domain) Let’s hope it’s not too broken …

**Comment by tailhook** [comment]
Great. Thanks!
